### ISSUE TITLE
HTTP 400 Bad Request at home.tsx:58

### ISSUE THREAD

**Issue by rvhuang** [Asing1001/movieRater.React#2]
After several searching, URL **/graphql** starts respond HTTP 400 Bad Request and autocomplete gets laggy.

**Comment by Asing1001** [comment]
It occur when user hit enter after typing, which expect to show movie list, will add as next release feature.

**Comment by Asing1001** [comment]
Fixed via 3a3b9c4c57ae0b904258415a0f5e4bec6dcbe886
